name: refresh-versions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - run: chmod +x gradlew
      - run: ./gradlew refreshVersions
      - uses: peter-evans/create-pull-request@v6
